sudo: required
services:
  - docker

before_install:
  - docker build -t lukicalk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lukicalk/react-test npm test -- --coverage

after_success:
  - docker build -t lukicalk/multi-client -f ./client
  - docker build -t lukicalk/multi-ngnix  ./ngnix
  - docker build -t lukicalk/multi-server ./server
  - docker build -t lukicalk/multi-worker ./worker
# Log in to the docker CLI, second attempt
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push lukicalk/multi-client
  - docker push lukicalk/multi-ngnix
  - docker push lukicalk/multi-server
  - docker push lukicalk/multi-worker



